name: bd

services:

  db:
    image: postgres:16
    container_name: bd_db
    environment:
      POSTGRES_DB: flights_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # TODO: porta cambiata su host perche 5432 era occupata
    ports:
      - "5433:5432"
    # caricare gli script di inizializzazione
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - bd-network
    # Al primo avvio, il database aspetta qualche secondo per finire di configurarsi
    healthcheck:
      # controlla che il db sia pronto e che l'utente guest esista
      test: ["CMD-SHELL", "pg_isready -U postgres -d flights_db && psql -U postgres -d flights_db -tAc \"SELECT 1 FROM pg_roles WHERE rolname='guest'\" | grep -q 1"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bd_backend
    ports:
    # TODO: porte occupate cambiate da 5000 a 5001
      - "5001:5001"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      # - DATABASE_URL=postgresql://postgres:password@db:5432/flights_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - bd-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bd_frontend
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
      - ./frontend:/app         # Mount source code
      - /app/node_modules       # Keep node_modules inside container
    environment:
      - NODE_ENV=development    # log + dettagliato (dev environment)
    networks:
      - bd-network

networks:
  bd-network:
    driver: bridge
